name: asuka
description: Show Snackbars, dialogs, ModalSheets and more in a single provider. Simple and Clean.
version: 2.0.2
homepage: https://github.com/Flutterando/asuka

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=3.7.0 <4.0.0"

dependencies:    
  flutter:
    sdk:  flutter
  
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutterando_analysis: ^0.0.2
  

flutter:
