name: asuka
description: Show Snackbars, dialogs, ModalSheets in a single provider. Simple and Clean.
version: 2.0.1
homepage: https://github.com/Flutterando/asuka

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=2.3.0 <4.0.0"

dependencies:    
  flutter:
    sdk:  flutter
  
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutterando_analysis: 
    git: https://github.com/Flutterando/flutterando_analysis.git
  

flutter:
