name: asuka
description: Show Snackbars, Dialogs, ModalSheets in a single provider. Simple and Clean.
version: 2.0.0+2
homepage: https://github.com/Flutterando/asuka

environment:
  sdk: ">=2.14.0-0 <3.0.0"
  flutter: ">=2.3.0 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter 
    
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
